version: "3"

services:
  server:
    restart: on-failure
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 4000:4000
      - 63240:63240
      - 63241:63241
    logging:
      driver: "json-file"
      options:
        max-size: "300m"
        max-file: "10"